spring.datasource.url=jdbc:mysql://localhost:3306/parkZen
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

parkVehicle()
Receive Request
?
Validate Vehicle Number
?
Validate Vehicle Type
?
Check Vehicle Already Parked?
?
Find Available Slot
?
Slot Found?
    / \
   /   \
 Yes   No
|       |
|       ?
|   SlotNotAvailableException
|
?
Create Ticket
?
Mark Slot Occupied
?
Return Ticket



POST /api/parking/exit

1. Find ticket by ticketId

2. Ticket exists?
No ? InvalidTicketException

3. Status ACTIVE?
No ? VehicleAlreadyExitedException

4. Calculate fee

5. Update ticket
exit_time
fee
status=COMPLETED

6. Free slot

7. Return response