spring.datasource.url=jdbc:mysql://localhost:3306/parkZen
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

No slot available
Invalid ticket
Duplicate vehicle entry
Vehicle already exited
Vehicle type mismatch
Invalid vehicle number
